---
- hosts: all
  gather_facts: yes
  become: true

  tasks:
    # Install Rails.

    - name: Install rails dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - zlib1g-dev
        - libsqlite3-dev
        - ruby
        - ruby-dev
        - rubygems
        - nodejs
        - nginx
        - ruby-passenger
        - ruby-railties
        - software-properties-common

    - name: Upgrade everything 
      apt:
        name: "*"
        state: latest
        force_apt_get: True

    - name: Gem Build one
      shell: |
         gem install bundle
    - name: Gem build two
      shell: |
         gem install rails
